const { withDangerousMod, withInfoPlist, withPlugins } = require('@expo/config-plugins');
const fs = require('fs');
const path = require('path');

/**
 * Config plugin to ensure iOS AppIcon asset catalog has all required icon sizes
 * and CFBundleIconName is set in Info.plist
 * 
 * This plugin MUST run AFTER Expo's icon generation plugins to ensure
 * our changes are not overwritten.
 */
const withIosIcons = (config) => {
  // First, ensure CFBundleIconName is in Info.plist using withInfoPlist
  config = withInfoPlist(config, (config) => {
    if (!config.modResults.CFBundleIconName) {
      config.modResults.CFBundleIconName = 'AppIcon';
    }
    return config;
  });

  // Then, update the asset catalog AFTER all other plugins
  // Use withDangerousMod to run at the very end of the prebuild process
  return withDangerousMod(config, [
    'ios',
    async (config) => {
      const platformRoot = config.modRequest.platformProjectRoot;
      
      // Try to find the app directory (could be 'spotx' or based on slug)
      const appName = config.slug || 'spotx';
      const appIconPath = path.join(
        platformRoot,
        appName,
        'Images.xcassets/AppIcon.appiconset/Contents.json'
      );
      const infoPlistPath = path.join(platformRoot, appName, 'Info.plist');

      console.log(`[withIosIcons] Platform root: ${platformRoot}`);
      console.log(`[withIosIcons] Looking for AppIcon at: ${appIconPath}`);

      // Update AppIcon asset catalog
      if (fs.existsSync(appIconPath)) {
        const appIconDir = path.dirname(appIconPath);
        const icon1024Path = path.join(appIconDir, 'App-Icon-1024x1024@1x.png');
        
        // Verify the icon file exists - this is critical for CompileAssetCatalogVariant
        if (!fs.existsSync(icon1024Path)) {
          console.error(`[withIosIcons] ❌ ERROR: Icon file not found: ${icon1024Path}`);
          console.error('[withIosIcons] This will cause CompileAssetCatalogVariant to fail during archive!');
          console.error('[withIosIcons] Expected icon file should be generated by Expo during prebuild.');
          
          // Try to find the icon in alternative locations
          const possiblePaths = [
            path.join(platformRoot, appName, 'Images.xcassets/AppIcon.appiconset/App-Icon-1024x1024@1x.png'),
            path.join(platformRoot, 'spotx/Images.xcassets/AppIcon.appiconset/App-Icon-1024x1024@1x.png'),
          ];
          
          let foundIcon = false;
          for (const possiblePath of possiblePaths) {
            if (fs.existsSync(possiblePath)) {
              console.log(`[withIosIcons] Found icon at alternative location: ${possiblePath}`);
              // Copy to expected location
              fs.copyFileSync(possiblePath, icon1024Path);
              console.log(`[withIosIcons] ✅ Copied icon to expected location`);
              foundIcon = true;
              break;
            }
          }
          
          if (!foundIcon) {
            throw new Error(
              `[withIosIcons] Icon file App-Icon-1024x1024@1x.png not found in AppIcon.appiconset directory. ` +
              `This will cause the build to fail. Make sure Expo's icon generation plugin runs before this plugin.`
            );
          }
        } else {
          // Verify the icon file is valid (not empty)
          try {
            const stats = fs.statSync(icon1024Path);
            if (stats.size === 0) {
              throw new Error(`Icon file is empty: ${icon1024Path}`);
            }
            console.log(`[withIosIcons] ✅ Icon file exists and is valid (${stats.size} bytes)`);
          } catch (error) {
            console.error(`[withIosIcons] ❌ ERROR: Cannot read icon file: ${error.message}`);
            throw error;
          }
        }
        
        const contents = {
          images: [
            {
              filename: 'App-Icon-1024x1024@1x.png',
              idiom: 'iphone',
              scale: '2x',
              size: '60x60'
            },
            {
              filename: 'App-Icon-1024x1024@1x.png',
              idiom: 'iphone',
              scale: '3x',
              size: '60x60'
            },
            {
              filename: 'App-Icon-1024x1024@1x.png',
              idiom: 'iphone',
              scale: '2x',
              size: '120x120'
            },
            {
              filename: 'App-Icon-1024x1024@1x.png',
              idiom: 'iphone',
              scale: '3x',
              size: '120x120'
            },
            {
              filename: 'App-Icon-1024x1024@1x.png',
              idiom: 'ipad',
              scale: '1x',
              size: '76x76'
            },
            {
              filename: 'App-Icon-1024x1024@1x.png',
              idiom: 'ipad',
              scale: '2x',
              size: '76x76'
            },
            {
              filename: 'App-Icon-1024x1024@1x.png',
              idiom: 'ipad',
              scale: '2x',
              size: '83.5x83.5'
            },
            {
              filename: 'App-Icon-1024x1024@1x.png',
              idiom: 'ipad',
              scale: '1x',
              size: '152x152'
            },
            {
              filename: 'App-Icon-1024x1024@1x.png',
              idiom: 'ipad',
              scale: '2x',
              size: '152x152'
            },
            {
              filename: 'App-Icon-1024x1024@1x.png',
              idiom: 'ipad',
              scale: '2x',
              size: '167x167'
            },
            {
              filename: 'App-Icon-1024x1024@1x.png',
              idiom: 'ios-marketing',
              platform: 'ios',
              scale: '1x',
              size: '1024x1024'
            }
          ],
          info: {
            version: 1,
            author: 'expo'
          }
        };

        fs.writeFileSync(appIconPath, JSON.stringify(contents, null, 2));
        console.log('[withIosIcons] ✅ Updated AppIcon asset catalog with all required sizes');
      } else {
        console.warn(`[withIosIcons] ⚠️ AppIcon path not found: ${appIconPath}`);
        // Try alternative path
        const altPath = path.join(platformRoot, 'spotx/Images.xcassets/AppIcon.appiconset/Contents.json');
        if (fs.existsSync(altPath)) {
          console.log(`[withIosIcons] Found alternative path: ${altPath}`);
          // Note: We don't update alternative paths to avoid confusion
          // The main path should be used
        } else {
          console.warn('[withIosIcons] ⚠️ AppIcon asset catalog not found. Expo should generate this during prebuild.');
        }
      }

      // Also ensure Info.plist has CFBundleIconName (backup check)
      if (fs.existsSync(infoPlistPath)) {
        const plistContent = fs.readFileSync(infoPlistPath, 'utf8');
        if (!plistContent.includes('<key>CFBundleIconName</key>')) {
          // Add CFBundleIconName after CFBundleDisplayName
          const updatedContent = plistContent.replace(
            /(<key>CFBundleDisplayName<\/key>\s*<string>.*?<\/string>)/,
            '$1\n    <key>CFBundleIconName</key>\n    <string>AppIcon</string>'
          );
          fs.writeFileSync(infoPlistPath, updatedContent);
          console.log('[withIosIcons] ✅ Added CFBundleIconName to Info.plist');
        } else {
          console.log('[withIosIcons] ✅ CFBundleIconName already exists in Info.plist');
        }
      } else {
        console.warn(`[withIosIcons] ⚠️ Info.plist not found: ${infoPlistPath}`);
      }

      return config;
    },
  ]);
};

module.exports = withIosIcons;
