#!/bin/bash

# Setup script for SpotX Merchant Portal
# This script creates the .env.local file with Supabase credentials

echo "🚀 Setting up SpotX Merchant Portal..."
echo ""

# Check if .env.local already exists
if [ -f ".env.local" ]; then
    echo "⚠️  .env.local already exists!"
    read -p "Do you want to overwrite it? (y/N): " -n 1 -r
    echo
    if [[ ! $REPLY =~ ^[Yy]$ ]]; then
        echo "Setup cancelled."
        exit 0
    fi
fi

# Get Supabase URL from parent config
SUPABASE_URL="https://mxdpiqnkowcxbujgrfom.supabase.co"
SUPABASE_ANON_KEY="eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im14ZHBpcW5rb3djeGJ1amdyZm9tIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjgwNjg2OTIsImV4cCI6MjA4MzY0NDY5Mn0.-KxgreAS7P2Ht5cq59yT9Zt0Be8C_l0SSrKFlqeMu-s"

# Create .env.local
cat > .env.local << EOF
# Supabase Configuration
# Generated by setup.sh on $(date)

NEXT_PUBLIC_SUPABASE_URL=${SUPABASE_URL}
NEXT_PUBLIC_SUPABASE_ANON_KEY=${SUPABASE_ANON_KEY}
EOF

echo "✅ Created .env.local"
echo ""
echo "📦 Installing dependencies..."
npm install

echo ""
echo "✨ Setup complete!"
echo ""
echo "To start the development server:"
echo "  npm run dev"
echo ""
echo "To test the merchant portal:"
echo "  1. Open http://localhost:3000"
echo "  2. Click 'Registrieren' to create a merchant account"
echo "  3. Follow the testing guide in docs/MERCHANT_PORTAL_TESTING.md"
echo ""
